# Generated by Django 5.0 on 2023-12-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avocat',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.AddField(
            model_name='avocat',
            name='langue',
            field=models.TextField(default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='avocat',
            name='password',
            field=models.TextField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
