# Generated by Django 5.0 on 2024-01-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_avocat_categories_remove_client_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='specialisation',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='avocat',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='avocat',
            name='langue',
        ),
        migrations.RemoveField(
            model_name='avocat',
            name='specialisation',
        ),
        migrations.AddField(
            model_name='avocat',
            name='langue',
            field=models.ManyToManyField(blank=True, to='app1.langue'),
        ),
        migrations.AddField(
            model_name='avocat',
            name='specialisation',
            field=models.ManyToManyField(blank=True, to='app1.specialisation'),
        ),
    ]
