# Generated by Django 5.0 on 2024-01-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_avocat_email_alter_avocat_langue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
