# Generated by Django 5.0 on 2024-01-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_langue_specialisation_rename_username_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
