# Generated by Django 5.0 on 2024-02-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_avocat_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mobile',
        ),
    ]
