# Generated by Django 5.0 on 2024-01-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_client_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='user_name',
        ),
    ]
