# Generated by Django 5.0 on 2024-01-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_client_options_remove_client_numero_tlfn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilavocat',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='profil_avocat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='app1.profilavocat'),
        ),
    ]
